button modified
immattdavison/NoMoreDomains pull request #69
Opened 2022-10-06 12:31 UTC by Priyansh61

The toggle button has been modified to the below button

### Proof:

https://user-images.githubusercontent.com/96513964/194313267-b46d1701-1728-434b-8e37-f20d053d0e4c.mp4

2022-10-06 12:32 UTC, Priyansh61 commented
Hey @immattdavison  I have added a new branch to keep the commits clean and synced with the master branch.

2022-10-06 12:34 UTC, immattdavison commented
> Hey @immattdavison I have added a new branch to keep the commits clean and synced with the master branch.

Hey @Priyansh61 I see you have tested this as a webpage, could you show it as a browser extension so that we can view the functionality

2022-10-06 14:40 UTC, Priyansh61 commented
https://user-images.githubusercontent.com/96513964/194342547-c6e0ca63-accd-42fa-98af-eaef356f1383.mp4

Is this al right @immattdavison ?

2022-10-06 15:18 UTC, immattdavison commented
I like that!

2022-10-06 17:19 UTC, Priyansh61 commented
Thanks a lot @immattdavison  for guiding me.

Do i need to make any further changes?

2022-10-07 13:05 UTC, immattdavison requested changes

2022-10-07 13:05 UTC, immattdavison commented on popup.html
> +  <link rel="icon" href="assets/icon.png" />
this is not necessary - please remove

2022-10-07 13:05 UTC, immattdavison commented on popup.html
> +  <style>
This style tag serves no purpose

2022-10-07 13:32 UTC, Priyansh61 commented on popup.html
> +  <style>
removed all the unecessary elements

2022-10-07 13:33 UTC, Priyansh61 commented
@immattdavison I have made all the requested changes, PTAL!

2022-10-07 14:35 UTC, merged

2022-10-07 14:52 UTC, Priyansh61 commented
@immattdavison Thank you so much... Learnt a lot from you :smile: 

Do let me know if  there is any other issue for me to work on ?

2022-10-07 14:55 UTC, immattdavison commented
I'd say just take a look through the current issues, I know #65 needs some help